### ISSUE TITLE
Unable to find "tasks.js" file, please check it again

### ISSUE THREAD

**Issue by laggingreflex** [start-runner/start#24]
The tasks file in the docs uses ES6 syntax (import/export), which start-cli is not able to parse natively by default which makes it gives a slightly misleading error: Unable to find "tasks.js" file, please check it again

It should give a more faithful error, like "unable to parse" or something. The docs probably should also use ES5 syntax? 

Awesome project btw, just found it and trying it out.

**Comment by deepsweet** [comment]
thanks for the report and PR, I'll take a look later today and will fix this issue for sure, it's definitely a bug.

>Awesome project btw

glad you like it :)

**Comment by deepsweet** [comment]
https://github.com/start-runner/simple-cli/releases/tag/v4.1.1
