### ISSUE TITLE
Basic plugins need 

### ISSUE THREAD

**Issue by TryHardNinja** [start-runner/start#34]
https://github.com/start-runner/postcss
please add basic plugin for frontend as like postcss, sass, stylus
I will be grateful for the plugin for rollup-buddler
Your project is not very popular due to lack of documentation. But I really like the idea. Very convenient api

**Comment by deepsweet** [comment]
Hi.

>postcss, sass, stylus, rollup

I can do `plugin-lib-postcss` and `plugin-lib-rollup` by myself, not sure about Sass and Stylus though – are they really still in use?

>lack of documentation

How it would look like in your opinion? Which sections it should have, what should be explained in more details? I'm open for any suggestions and agree that the current state is not as friendly as it could be.

>I really like the idea. Very convenient api

Good to hear :) Please let me know if you have any issues or ideas.

**Comment by TryHardNinja** [comment]
> I can do plugin-lib-postcss and plugin-lib-rollup by myself, not sure about Sass and Stylus though – are they really still in use?

sass, stylus they are not so important. But postcss covers most of the tasks
I will very much wait for postcss. Now I understand that I can not start a project without him

> How it would look like in your opinion? Which sections it should have, what should be explained in more details? I'm open for any suggestions and agree that the current state is not as friendly as it could be.

As for the documentation, I'll think about it
I'll try to make examples or find the best options

PS Sorry for my English

**Comment by deepsweet** [comment]
I've created two separate issues regarding `plugin-lib-postcss` and `plugin-lib-rollup`, both should be done next week:

* https://github.com/deepsweet/start/issues/35
* https://github.com/deepsweet/start/issues/36

**Comment by TryHardNinja** [comment]
I will wait

**Comment by deepsweet** [comment]
I've just published [plugin-lib-postcss](https://github.com/deepsweet/start/tree/master/packages/plugin-lib-postcss) 📦

**Comment by deepsweet** [comment]
[plugin-lib-rollup](https://github.com/deepsweet/start/tree/master/packages/plugin-lib-rollup) 📦

>As for the documentation, I'll think about it
>I'll try to make examples or find the best options

Please do and open a separate issue 🙏
