### ISSUE TITLE
Logo help

### ISSUE THREAD

**Issue by Batarian711** [start-runner/start#39]
I'm a graphic designer. I design a volunteer logo. I can design it for you.

**Comment by deepsweet** [comment]
Hi.

I like the current logo but at the same time I'm open for something new :) Do you have any examples or sketches?

**Comment by Batarian711** [comment]
I designed two logos in minimalist and icon style to better reflect your progeny. What do you think? Which one do you prefer?

![start](https://user-images.githubusercontent.com/41051393/42832887-531fb928-89fb-11e8-9918-ba43cec479e3.jpg)

**Comment by deepsweet** [comment]
My vision of Start as a task runner is more about a button that starts something. I think that I'm going to stick with the current logo, but thank you very much for your proposal and time 🤝
