### ISSUE TITLE
Wrong plugin type?

### ISSUE THREAD

**Issue by simonedavico** [start-runner/start#40]
I was going through the [plugin types file](https://github.com/deepsweet/start/blob/master/packages/plugin/src/index.ts) and I was wondering: shouldn't the return type of [the default export](https://github.com/deepsweet/start/blob/master/packages/plugin/src/index.ts#L28) be `StartPlugin` or `StartPluginAsync` instead of `StartPluginSync`? 

Since the default export is an *async function expression*, it will implicitly use a Promise to return its result.

**Comment by deepsweet** [comment]
Hi.

Yeah, I know, it feels a bit messy at the first glance. But:

```js
export default (value: any, message?: string) =>
  plugin('assert', async () => {
    const { default: assertLib } = await import('assert')

    assertLib(value, message)
  })
```

`plugin` wrapper itself is sync, it's internal callback is async. Otherwise `plugin` is not callable and should be awaited first before becoming a function.

**Comment by deepsweet** [comment]
Hm, maybe I'm wrong. Will play with the types and see.

**Comment by simonedavico** [comment]
Yep, the fact that the internal callback is async is taken care by the fact that `StartPluginFn` can return a `Promise<StartPluginPropsOut>`.

Unless I'm reading typescript wrong (I never actually wrote ts :D) the return type at line 28 refers to the async function declared just after, so it should definitely be `Promise<StartPluginSync>`, or at least `StartPlugin` :) btw, thank you for the quick response, really enjoying this library!

**Comment by deepsweet** [comment]
"Fixed" with renaming "Sync" to "Async" :) The rest is fine – async function is a function that returns a promise, which matches `StartPluginAsync` just fine.

>thank you for the quick response, really enjoying this library!

Glad you like it 👌

**Comment by simonedavico** [comment]
Oh I understand, so it's also possible to define a plugin as a Promise that gets resolved to a `StartPluginAsync` function, right? Much clearer now, thanks!

**Comment by deepsweet** [comment]
Yeah, there are really "async" plugins, my personal use case is so called "sub-tasks" (I know, I suck at documentation and things like that are almost not documented anywhere):

```js
export const task1 = async () => {
  const { default: config } = await import('./config')

  // ...
}

export const task2 = () =>
  sequence(
    plugin1(),
    task1(),
    plugin2()
  )
```

In this case `task1()` is a Promise that returns some plugin(s).
