### ISSUE TITLE
Angular

### ISSUE THREAD

**Issue by viceice** [start-runner/start#47]
How to use angular cli with this project?

**Comment by deepsweet** [comment]
Hi.

I have literally zero experience with Angular in general and its CLI in particular. Even if it doesn't have a promise based API it's possible to write a Start plugin for it using [`execa`](https://github.com/sindresorhus/execa).

**Comment by viceice** [comment]
ok, nice tip, i will try execa within start

**Comment by viceice** [comment]
Can i use [spawn plugin](https://github.com/deepsweet/start/tree/master/packages/plugin-spawn) for calling angular-cli or even a yarn script?

**Comment by deepsweet** [comment]
Spawn plugin should work just fine.

**Comment by viceice** [comment]
I have a tsconfig in my project root, is that used by babel or start?

**Comment by deepsweet** [comment]
It's used only by TypeScript itself, either by `tsc` CLI or by editor integration, such as VSCode.

**Comment by viceice** [comment]
ok, I've mode the `tasks.t`s to a subfolder with a custom `tsconfig.json`. Do i need babel if i write my task as plain javascript?

**Comment by deepsweet** [comment]
Babel doesn't use tsconfig or anything related to TS at all to transpile code, so that TS only "validate" codebase and Babel only transpile it.

**Comment by deepsweet** [comment]
did you manage to run it through spawn plugin?

**Comment by viceice** [comment]
yes, simply using this:

```typescript
export const ngBuild = (app: string, ...args: string[]) => spawn(['ng', 'build', app, ...args]);
```
