### ISSUE TITLE
Is the dead simple task runner literally dead now?

### ISSUE THREAD

**Issue by nikolay** [start-runner/start#5]

**Comment by deepsweet** [comment]
no, just waiting for some feature request or bug report :) `start` works fine for me, but it seems like no one else uses it a lot...

**Comment by nikolay** [comment]
@deepsweet Which is a pity as it really is how things should be done in 2016!

**Comment by deepsweet** [comment]
do you have _any_ suggestions or ideas? existing amount of tasks completely meet my personal needs in all projects.

**Comment by nikolay** [comment]
@deepsweet I think the project needs more awareness and maybe a simple landing page. I will try to promote it wherever I can.

**Comment by eisisig** [comment]
I'm using it and loving the concept. Sexy landing page. Maybe a sample using "tasks" in multiple files etc...

I will promote this when I can as a good "run" tool

**Comment by deepsweet** [comment]
I slowly move toward the sexy landing page with some kind of "recipes" section along with a list of available tasks. All the tasks were reviewed (and some of them were completely refactored) last month, so I'll be ready to spend some time for the "website" pretty soon.

**Comment by deepsweet** [comment]
it's definitely not, see master branch.
